Implement bucket region finding for git-credentials-s3-secrets

diff --git a/git-credential-s3-secrets b/git-credential-s3-secrets
--- a/git-credential-s3-secrets
+++ b/git-credential-s3-secrets
@@ -52,10 +52,42 @@ parse_url() {
   done
 }
 
+s3_bucket_region() {
+  local bucket="$1"
+
+  local guess_region="${AWS_DEFAULT_REGION:-}"
+  if [ -z "${guess_region}" ]
+  then
+    # This plug-in may not be executing in an AWS VPC or have access to the IDMS
+    # Fail fast with the --connect-timeout flag
+    local token=$(curl -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 60" --fail --silent --show-error --location --connect-timeout 10 http://169.254.169.254/latest/api/token)
+    if [ -n "${token}" ]
+    then
+      guess_region=$(curl -H "X-aws-ec2-metadata-token: $token" --fail --silent --show-error --location http://169.254.169.254/latest/meta-data/placement/region)
+    fi
+  fi
+  if [ -z "${guess_region}" ]
+  then
+    guess_region="us-east-1"
+  fi
+
+  local bucket_region="$(aws s3api get-bucket-location --bucket "${bucket}" --region "${guess_region}" --output text)"
+
+  echo "${bucket_region}"
+}
+
 s3_download() {
   local bucket="$1"
   local key="$2"
-  local aws_s3_args=("--quiet" "--region=$AWS_DEFAULT_REGION")
+
+  local bucket_region="$(s3_bucket_region "${bucket}")"
+  if [ -z "${bucket_region}" ]
+  then
+    echo "Could not determine the bucket region for ${bucket}"
+    exit 2
+  fi
+
+  local aws_s3_args=("--quiet" "--region=${bucket_region}")
 
   if [[ "${BUILDKITE_USE_KMS:-true}" =~ ^(true|1)$ ]] ; then
     aws_s3_args+=("--sse" "aws:kms")
