Log errors to stderr

diff --git a/git-credential-s3-secrets b/git-credential-s3-secrets
--- a/git-credential-s3-secrets
+++ b/git-credential-s3-secrets
@@ -83,7 +83,7 @@ s3_download() {
   local bucket_region="$(s3_bucket_region "${bucket}")"
   if [ -z "${bucket_region}" ]
   then
-    echo "Could not determine the bucket region for ${bucket}"
+    echo "Could not determine the bucket region for ${bucket}" >&2
     exit 2
   fi
 
