Remove header for warn (suggested by @matthewd)

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -77,7 +77,7 @@ if [[ -n "$s3_bucket" ]] ; then
       eval "$envscript"
       set +o allexport
     elif [[ $? -eq 2 ]] ; then
-      echo "+++ :warning: Failed to check if $key exists" >&2;
+      echo "Failed to check if $key exists" >&2;
     fi
   done
 
