Added a basic test

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -7,11 +7,7 @@ s3_exists() {
   local key="$2"
   local aws_s3_args=("--region=$AWS_DEFAULT_REGION")
 
-  if [[ -n "${BUILDKITE_SECRETS_KEY:-}" ]] ; then
-    aws_s3_args+=("--sse-customer-algorithm" "AES256" "--sse-customer-key" "${BUILDKITE_SECRETS_KEY}")
-  fi
-
-  if ! env -i aws s3api head-object "${aws_s3_args[@]}" --bucket "$bucket" --key "$key" &>/dev/null ; then
+  if ! aws s3api head-object "${aws_s3_args[@]}" --bucket "$bucket" --key "$key" &>/dev/null ; then
     return 1
   fi
 }
@@ -21,16 +17,22 @@ s3_download() {
   local key="$2"
   local aws_s3_args=("--quiet" "--region=$AWS_DEFAULT_REGION")
 
-  if [[ -n "${BUILDKITE_SECRETS_KEY:-}" ]] ; then
-    aws_s3_args+=("--sse-c" "AES256" "--sse-c-key" "${BUILDKITE_SECRETS_KEY}")
-  elif [[ "${BUILDKITE_USE_KMS:-true}" =~ ^(true|1)$ ]] ; then
+  if [[ "${BUILDKITE_USE_KMS:-true}" =~ ^(true|1)$ ]] ; then
     aws_s3_args+=("--sse" "aws:kms")
   fi
 
-  if ! env -i aws s3 cp "${aws_s3_args[@]}" "s3://$1/$2" /dev/stdout ; then
+  if ! aws s3 cp "${aws_s3_args[@]}" "s3://$1/$2" /dev/stdout ; then
     exit 1
   fi
 }
+
+safe_env_export() {
+  sed -E -n 's/[^#]+/export &/ p'
+}
+
+if [[ -z "${AWS_DEFAULT_REGION:-}" ]] ; then
+  export AWS_DEFAULT_REGION=us-east-1
+fi
 
 s3_bucket="${BUILDKITE_PLUGIN_SECRETS_S3_BUCKET:-}"
 s3_bucket_prefix="${BUILDKITE_PLUGIN_SECRETS_S3_BUCKET_PREFIX:-$BUILDKITE_PIPELINE_SLUG}"
@@ -40,6 +42,8 @@ eval "$(ssh-agent -s)"
 echo
 
 if [[ -n "$s3_bucket" ]] ; then
+  echo "~~~ Downloading secrets from s3 bucket $s3_bucket" >&2;
+
   ssh_key_paths=(
     "$s3_bucket_prefix/private_ssh_key"
     "$s3_bucket_prefix/id_rsa_github"
@@ -49,41 +53,46 @@ if [[ -n "$s3_bucket" ]] ; then
 
   for key in ${ssh_key_paths[*]} ; do
     if s3_exists "${s3_bucket}" "$key" ; then
-      echo "~~~ Downloading ssh-key from ${key}"
+      echo "~~~ Downloading ssh-key from ${key}" >&2;
       if ! ssh_key=$(s3_download "${s3_bucket}" "$key") ; then
-        echo "~~~ :warning: Failed to download ssh-key $key"
+        echo "~~~ :warning: Failed to download ssh-key $key" >&2;
         exit 1
       fi
+      echo "~~~ Loading ssh-key into ssh-agent ${SSH_AGENT_PID:-}" >&2;
       SSH_ASKPASS="/bin/false" ssh-add <(echo "$ssh_key")
       key_found=1
-      break
     fi
   done
 
   if [[ -z "${key_found:-}" ]] && [[ "${BUILDKITE_REPO:-}" =~ ^git ]] ; then
-    echo "~~~ :warning: Failed to find an SSH key in secret bucket"
+    echo "~~~ :warning: Failed to find an SSH key in secret bucket" >&2;
     exit 1
   fi
 
   env_paths=(
-    "env"
-    "environment"
     "${s3_bucket_prefix}/env"
     "${s3_bucket_prefix}/environment"
+    "env"
+    "environment"
   )
+
+  env_before="$(env | sort)"
 
   for key in ${env_paths[*]} ; do
     if s3_exists "${s3_bucket}" "$key" ; then
-      echo "~~~ Downloading env file from $key"
+      echo "~~~ Downloading env file from $key" >&2;
       if ! envvars=$(s3_download "${s3_bucket}" "$key") ; then
-        echo "~~~ :warning: Failed to download env from $key"
+        echo "~~~ :warning: Failed to download env from $key" >&2;
         exit 1
       fi
-      set -a
-      eval "$envvars"
-      set +a
+      eval "$(safe_env_export <<< "$envvars")"
     fi
   done
+
+  if [[ "${BUILDKITE_PLUGIN_SECRETS_DUMP_ENV:-1}" =~ ^(true|1)$ ]] ; then
+    echo "~~~ Environment variables that were set" >&2;
+    comm -13 <(echo "$env_before") <(env | sort) || true
+  fi
 
   git_credentials_paths=(
     "git-credentials"
@@ -92,12 +101,12 @@ if [[ -n "$s3_bucket" ]] ; then
 
   for key in ${git_credentials_paths[*]} ; do
     if s3_exists "${s3_bucket}" "$key" ; then
-      echo "~~~ Downloading git-credentials files"
+      echo "~~~ Downloading git-credentials files" >&2;
       if ! envvars=$(s3_download "${s3_bucket}" "$key") ; then
-        echo "~~~ :warning: Failed to download git-credentials from $key"
+        echo "~~~ :warning: Failed to download git-credentials from $key" >&2;
         exit 1
       fi
-      mv "$key" .git-credentials
+      echo "$key" > .git-credentials
       git config credential.helper "store --file=$PWD/.git-credentials"
     fi
   done
